export const countries = [
    { uf: "AF", description: "Afeganistão" },
    { uf: "AL", description: "Albânia" },
    { uf: "DE", description: "Alemanha" },
    { uf: "AD", description: "Andorra" },
    { uf: "AO", description: "Angola" },
    { uf: "AI", description: "Anguilla" },
    { uf: "AQ", description: "Antártida" },
    { uf: "AG", description: "Antígua e Barbuda" },
    { uf: "AN", description: "Antilhas Holandesas" },
    { uf: "SA", description: "Arábia Saudita" },
    { uf: "DZ", description: "Argélia" },
    { uf: "AR", description: "Argentina" },
    { uf: "AM", description: "Armênia" },
    { uf: "AW", description: "Aruba" },
    { uf: "AU", description: "Austrália" },
    { uf: "AT", description: "Áustria" },
    { uf: "AZ", description: "Azerbaijão" },
    { uf: "BS", description: "Bahamas" },
    { uf: "BH", description: "Bahrein" },
    { uf: "BD", description: "Bangladesh" },
    { uf: "BB", description: "Barbados" },
    { uf: "BE", description: "Bélgica" },
    { uf: "BZ", description: "Belize" },
    { uf: "BJ", description: "Benin" },
    { uf: "BM", description: "Bermudas" },
    { uf: "BY", description: "Bielorrússia" },
    { uf: "BO", description: "Bolívia" },
    { uf: "BA", description: "Bósnia e Herzegovina" },
    { uf: "BW", description: "Botsuana" },
    { uf: "BR", description: "Brasil" },
    { uf: "BN", description: "Brunei" },
    { uf: "BG", description: "Bulgária" },
    { uf: "BF", description: "Burkina Faso" },
    { uf: "BI", description: "Burundi" },
    { uf: "BT", description: "Butão" },
    { uf: "CV", description: "Cabo Verde" },
    { uf: "KH", description: "Camboja" },
    { uf: "CM", description: "Camarões" },
    { uf: "CA", description: "Canadá" },
    { uf: "QA", description: "Catar" },
    { uf: "KZ", description: "Cazaquistão" },
    { uf: "TD", description: "Chade" },
    { uf: "CL", description: "Chile" },
    { uf: "CN", description: "China" },
    { uf: "CY", description: "Chipre" },
    { uf: "SG", description: "Cingapura" },
    { uf: "CO", description: "Colômbia" },
    { uf: "KM", description: "Comores" },
    { uf: "CG", description: "Congo" },
    { uf: "KP", description: "Coreia do Norte" },
    { uf: "KR", description: "Coreia do Sul" },
    { uf: "CI", description: "Costa do Marfim" },
    { uf: "CR", description: "Costa Rica" },
    { uf: "HR", description: "Croácia" },
    { uf: "CU", description: "Cuba" },
    { uf: "KW", description: "Kuait" },
    { uf: "LA", description: "Laos" },
    { uf: "LS", description: "Lesoto" },
    { uf: "LV", description: "Letônia" },
    { uf: "LB", description: "Líbano" },
    { uf: "LR", description: "Libéria" },
    { uf: "LY", description: "Líbia" },
    { uf: "LI", description: "Liechtenstein" },
    { uf: "LT", description: "Lituânia" },
    { uf: "LU", description: "Luxemburgo" },
    { uf: "MK", description: "Macedônia" },
    { uf: "MG", description: "Madagascar" },
    { uf: "MY", description: "Malásia" },
    { uf: "MW", description: "Malaui" },
    { uf: "MV", description: "Maldivas" },
    { uf: "ML", description: "Mali" },
    { uf: "MT", description: "Malta" },
    { uf: "MA", description: "Marrocos" },
    { uf: "MQ", description: "Martinica" },
    { uf: "MU", description: "Maurício" },
    { uf: "MR", description: "Mauritânia" },
    { uf: "YT", description: "Mayotte" },
    { uf: "MX", description: "México" },
    { uf: "FM", description: "Micronésia" },
    { uf: "MZ", description: "Moçambique" },
    { uf: "MD", description: "Moldávia" },
    { uf: "MC", description: "Mônaco" },
    { uf: "MN", description: "Mongólia" },
    { uf: "ME", description: "Montenegro" },
    { uf: "MS", description: "Montserrat" },
    { uf: "MM", description: "Mianmar" },
    { uf: "NA", description: "Namíbia" },
    { uf: "NR", description: "Nauru" },
    { uf: "NP", description: "Nepal" },
    { uf: "NI", description: "Nicarágua" },
    { uf: "NE", description: "Níger" },
    { uf: "NG", description: "Nigéria" },
    { uf: "NU", description: "Niue" },
    { uf: "NO", description: "Noruega" },
    { uf: "NZ", description: "Nova Zelândia" },
    { uf: "OM", description: "Omã" },
    { uf: "PW", description: "Palau" },
    { uf: "PA", description: "Panamá" },
    { uf: "PG", description: "Papua-Nova Guiné" },
    { uf: "PK", description: "Paquistão" },
    { uf: "PY", description: "Paraguai" },
    { uf: "PE", description: "Peru" },
    { uf: "PN", description: "Pitcairn" },
    { uf: "PF", description: "Polinésia Francesa" },
    { uf: "PL", description: "Polônia" },
    { uf: "PT", description: "Portugal" },
    { uf: "PR", description: "Porto Rico" },
    { uf: "QA", description: "Catar" },
    { uf: "KG", description: "Quirguistão" },
    { uf: "RE", description: "Reunião" },
    { uf: "RO", description: "Romênia" },
    { uf: "RW", description: "Ruanda" },
    { uf: "RU", description: "Rússia" },
    { uf: "EH", description: "Saara Ocidental" },
    { uf: "WS", description: "Samoa" },
    { uf: "AS", description: "Samoa Americana" },
    { uf: "SM", description: "San Marino" },
    { uf: "SH", description: "Santa Helena" },
    { uf: "LC", description: "Santa Lúcia" },
    { uf: "PM", description: "Saint Pierre e Miquelon" },
    { uf: "VC", description: "São Vicente e Granadinas" },
    { uf: "ST", description: "São Tomé e Príncipe" },
    { uf: "SN", description: "Senegal" },
    { uf: "SL", description: "Serra Leoa" },
    { uf: "RS", description: "Sérvia" },
    { uf: "SC", description: "Seychelles" },
    { uf: "SY", description: "Síria" },
    { uf: "SO", description: "Somália" },
    { uf: "LK", description: "Sri Lanka" },
    { uf: "SZ", description: "Suazilândia" },
    { uf: "SD", description: "Sudão" },
    { uf: "SS", description: "Sudão do Sul" },
    { uf: "SE", description: "Suécia" },
    { uf: "CH", description: "Suíça" },
    { uf: "SR", description: "Suriname" },
    { uf: "TJ", description: "Tadjiquistão" },
    { uf: "TH", description: "Tailândia" },
    { uf: "TW", description: "Taiwan" },
    { uf: "TZ", description: "Tanzânia" },
    { uf: "TF", description: "Terras Austrais e Antárticas Francesas" },
    { uf: "IO", description: "Território Britânico do Oceano Índico" },
    { uf: "PS", description: "Território da Palestina" },
    { uf: "TL", description: "Timor-Leste" },
    { uf: "TG", description: "Togo" },
    { uf: "TK", description: "Tokelau" },
    { uf: "TO", description: "Tonga" },
    { uf: "TT", description: "Trinidad e Tobago" },
    { uf: "TN", description: "Tunísia" },
    { uf: "TM", description: "Turcomenistão" },
    { uf: "TR", description: "Turquia" },
    { uf: "TV", description: "Tuvalu" },
    { uf: "UA", description: "Ucrânia" },
    { uf: "UG", description: "Uganda" },
    { uf: "UY", description: "Uruguai" },
    { uf: "UZ", description: "Usbequistão" },
    { uf: "VU", description: "Vanuatu" },
    { uf: "VA", description: "Vaticano" },
    { uf: "VE", description: "Venezuela" },
    { uf: "VN", description: "Vietnã" },
    { uf: "WF", description: "Wallis e Futuna" },
    { uf: "ZM", description: "Zâmbia" },
    { uf: "ZW", description: "Zimbábue" }
];